"""
Privacy-aware optimization of fluid-antenna port-selection probabilities for
fluid-antenna-assisted dynamic directional modulation.

Author
------
Pedro E. Goria Silva

Module
------
fa_ddm.optimization

Purpose
-------
This module implements the reliability model and finite-grid optimization tools
used to design privacy-aware fluid-antenna port-selection probabilities in the
FA-DDM numerical framework.

The module provides reusable functions for:

1. evaluating the Gaussian Q-function;
2. computing coherent QPSK symbol-error probabilities at Bob for every
   candidate port;
3. constructing the port-linear Gaussian-mixture likelihood coefficients used
   by the quadrature approximation of Eve's posterior vulnerability; and
4. solving the privacy-aware port-selection problem as a linear program.

The optimization changes only the probability with which each candidate port
is activated. The single-radio-frequency-chain architecture, Bob-oriented
phase compensation, confidential constellation, transmit power, and physical
aperture remain fixed.

Operational objective
---------------------
For one realization of Bob's and Eve's channels, the activation-probability
vector is

    rho = [rho_1, ..., rho_N]^T,

subject to

    rho_n >= 0,
    sum_n rho_n = 1.

The privacy objective is Eve's posterior Bayes vulnerability, namely the
maximum probability that an optimal eavesdropper correctly identifies the
confidential symbol in one attempt.

After deterministic quadrature over Eve's complex observation plane, the
finite-grid objective has the form

    V_hat_E(rho)
        = sum_r omega_r max_m sum_n C[r, m, n] rho_n,

where:

    r           indexes quadrature nodes;
    m           indexes confidential symbols;
    n           indexes candidate fluid-antenna ports;
    omega_r     is the quadrature weight of node r;
    C[r,m,n]    is the prior-weighted Gaussian component density associated
                with symbol m and port n at node r.

The objective is convex because it is a nonnegative weighted sum of pointwise
maxima of affine functions of rho.

Bob-side reliability model
--------------------------
For coherent QPSK and active port n, Bob's instantaneous receive SNR is

    gamma_B,n = P_t |h_B,n|^2 / sigma_B^2,

where P_t is the transmit power, h_B,n is Bob's channel coefficient, and
sigma_B^2 is Bob's complex-noise variance.

The port-conditioned QPSK symbol-error probability is

    epsilon_B,n
        = 2 Q(sqrt(gamma_B,n))
          - Q(sqrt(gamma_B,n))^2.

Under activation distribution rho, Bob's average symbol-error probability is

    P_e,B(rho) = sum_n rho_n epsilon_B,n.

The privacy-aware design constrains this average error by

    P_e,B(rho) <= epsilon_B,

where epsilon_B is the maximum admissible Bob-side symbol-error probability.

If epsilon_B is smaller than the minimum port-conditioned error probability,
then no probability distribution can satisfy the reliability requirement and
the optimization problem is infeasible.

Gaussian Q-function
-------------------
The helper ``q_function`` evaluates

    Q(x) = (1 / 2) erfc(x / sqrt(2)).

The implementation accepts scalar or array-like real inputs and returns the
corresponding NumPy scalar or array generated by ``scipy.special.erfc``.

Likelihood coefficients
-----------------------
For confidential symbol s_m and port n, Eve's Gaussian-mixture centroid is

    mu_m,n = sqrt(P_t) g_n s_m,

where g_n is Eve's effective coefficient after Bob-oriented phase
compensation.

At quadrature observation y_r, the coefficient is

    C[r,m,n]
        = p_S(s_m) / (pi sigma_E^2)
          exp(-|y_r - mu_m,n|^2 / sigma_E^2).

For fixed nodes, channels, symbols, powers, noise variance, and symbol priors,
these coefficients are independent of rho. The prior-weighted symbol
likelihood is therefore affine in the activation probabilities:

    ell_m(y_r; rho) = sum_n C[r,m,n] rho_n.

The function ``likelihood_coefficients`` returns the complete coefficient
tensor with dimensions

    number of observations x number of symbols x number of ports.

Linear-program formulation
--------------------------
One epigraph variable t_r is introduced for every quadrature node. The
finite-grid optimization is

    minimize     sum_r omega_r t_r

    subject to   t_r >= sum_n C[r,m,n] rho_n,
                 for every node r and symbol m,

                 sum_n rho_n epsilon_B,n <= epsilon_B,

                 sum_n rho_n = 1,

                 rho_n >= 0.

The implementation stores the variables in the order

    [rho_1, ..., rho_N, t_1, ..., t_R].

The epigraph constraints are supplied to ``scipy.optimize.linprog`` in the
standard upper-inequality form

    A_ub x <= b_ub.

For each node-symbol pair, the implemented row is

    sum_n C[r,m,n] rho_n - t_r <= 0.

The reliability constraint is appended as the final upper-inequality row. The
probability normalization is represented by one equality constraint.

The problem is solved with the HiGHS backend through

    scipy.optimize.linprog(method="highs").

For a fixed quadrature grid, every solver optimum is global because the
objective and all constraints are affine.

Public functions
----------------
q_function
    Evaluates the Gaussian Q-function through the complementary error
    function.

qpsk_symbol_error_probabilities
    Computes coherent QPSK symbol-error probability for each Bob-channel
    coefficient.

likelihood_coefficients
    Constructs the prior-weighted Gaussian component tensor that makes every
    quadrature-node symbol likelihood affine in the port probabilities.

optimize_port_probabilities
    Constructs and solves the quadrature epigraph linear program and returns
    the optimal activation distribution, vulnerability objective, achieved
    Bob-side error, and solver status.

Input conventions
-----------------
bob_channel
    Nonempty one-dimensional complex array with one Bob-channel coefficient
    per candidate port.

symbols
    One-dimensional complex constellation array.

effective_eve_channel
    One-dimensional complex array with one effective Eve-side coefficient per
    candidate port.

symbol_probabilities
    One-dimensional prior-probability vector aligned with ``symbols``. Entries
    must sum to one.

transmit_power
    Strictly positive average transmit power.

noise_variance_bob
    Strictly positive complex Gaussian noise variance at Bob.

noise_variance_eve
    Strictly positive complex Gaussian noise variance at Eve.

bob_port_error_probabilities
    One-dimensional array containing one Bob-side symbol-error probability per
    candidate port.

maximum_bob_error
    Maximum admissible average Bob-side symbol-error probability.

points_per_axis
    Number of trapezoidal quadrature nodes along each real dimension of Eve's
    complex observation plane.

noise_margin_sigma
    Margin added around all Gaussian-mixture centroids when constructing the
    quadrature integration region.

Returned quantities
-------------------
``qpsk_symbol_error_probabilities`` returns

    error_probabilities
        Floating-point array containing the coherent QPSK symbol-error
        probability associated with every candidate port.

``likelihood_coefficients`` returns

    coefficients
        Three-dimensional array C[r,m,n] with shape ``(R, M, N)``.

``optimize_port_probabilities`` returns a dictionary containing:

    rho
        Globally optimal finite-grid port-selection probability vector.

    vulnerability
        Optimal quadrature objective value, equal to the finite-grid posterior
        vulnerability approximation.

    bob_error
        Average Bob-side symbol-error probability achieved by the optimized
        distribution.

    status
        Status message returned by the HiGHS linear-program solver.

Feasibility
-----------
The reliability constraint is feasible over the probability simplex if and
only if

    maximum_bob_error >= min_n epsilon_B,n.

The implementation checks this necessary and sufficient condition before
constructing the quadrature grid and raises a ``ValueError`` when the requested
threshold is infeasible, up to a numerical tolerance of 1e-12.

A feasible threshold does not imply that the reliability constraint is active
at the optimum. For sufficiently relaxed thresholds, the unconstrained privacy-
optimal distribution may already satisfy Bob's requirement.

Validation and numerical safeguards
-----------------------------------
The module validates nonempty Bob-channel arrays, positive transmit and noise
powers, prior-vector dimensions and normalization, Eve noise variance, Bob-
error-vector dimensions, and the minimum reliability-feasibility condition.

The optimizer raises a ``RuntimeError`` when the HiGHS solver does not report a
successful result. The solver message is included in the exception to support
diagnosis of numerical or formulation failures.

The returned probability vector is read directly from the solver result. Small
floating-point deviations from exact normalization or nonnegativity may occur
within solver tolerances. Experiment-level tests should verify the simplex and
reliability constraints using appropriate numerical tolerances.

Quadrature accuracy
-------------------
The optimized objective is exact for the selected finite quadrature grid but is
only an approximation of the continuous-observation posterior vulnerability.
Final manuscript results should be checked for convergence by increasing
``points_per_axis`` and ``noise_margin_sigma`` until both the objective and the
optimized probability vector are sufficiently stable.

A coarse grid may underestimate probability mass in the tails or alter the
piecewise-linear geometry of the finite-grid objective. The optimized policy
should therefore be evaluated independently, preferably through a refined
quadrature and the Monte Carlo attack-success estimator.

Computational complexity
------------------------
Let R be the total number of quadrature nodes, M the constellation order, and N
the number of candidate ports.

Coefficient construction requires O(R M N) Gaussian-kernel evaluations and
stores an array of the same asymptotic size.

The linear program contains

    N + R variables,
    R M + 1 upper-inequality constraints,
    1 equality constraint.

The current implementation constructs the inequality matrix as a dense NumPy
array. Memory use therefore scales as O(R M (N + R)), which can become large
for fine two-dimensional grids. Sparse-matrix construction should be considered
if substantially larger quadrature grids, constellations, or port sets are
required.

Reproducibility
---------------
This module contains no random-number generation. For fixed channels, symbols,
priors, powers, noise variances, Bob-side error probabilities, reliability
threshold, and quadrature settings, coefficient construction is deterministic.

The HiGHS solver is deterministic for the same problem data under the software
version and numerical environment used by the experiment. Channel seeds and
realizations are controlled by the experiment runner and YAML configuration.

CSI interpretation
------------------
Bob's instantaneous channel is required to compute the phase precoder and the
port-conditioned reliability costs.

The instantaneous privacy-aware probability adaptation additionally requires
Eve's effective channel coefficients. Because a passive eavesdropper's
instantaneous channel may be unavailable in practice, this design is interpreted
as a full-information benchmark that quantifies the maximum privacy gain
attainable through instantaneous channel-adaptive port probabilities.

If only Eve's channel distribution is available, an expected-vulnerability
objective can be constructed over channel realizations. Convexity is preserved
because expectation preserves convexity, but that statistical-CSI formulation
is not implemented by the present routine.

Modeling assumptions and limitations
------------------------------------
- Bob's symbol-error model is specific to coherent QPSK.
- Bob is assumed to know the effective gain required for coherent detection.
- The reliability constraint uses average symbol-error probability over active
  ports.
- Eve's vulnerability is evaluated for the supplied instantaneous effective
  channel.
- The linear program optimizes a finite quadrature approximation rather than an
  analytic continuous-plane integral.
- The implementation uses a dense constraint matrix.
- Hardware switching costs, mutual coupling, impedance mismatch, channel-
  estimation overhead, and imperfect CSI are not modeled.
- The optimization controls only port probabilities and does not change phase
  coefficients, transmit power, constellation, or physical port positions.
- A solver optimum may be sparse because a linear-program optimum can occur at
  an extreme point of the feasible polytope.

Notes
-----
The privacy objective is posterior vulnerability itself, not a surrogate based
on constellation spread, channel rank, secrecy rate, or Eve's conventional
symbol-error probability.

The quadrature weights are placed in the linear objective, while
``likelihood_coefficients`` contains prior-weighted component densities without
quadrature weights. This separation should be preserved if the implementation
is refactored.

The maximum admissible Bob error should be interpreted consistently with the
same symbol-error expression used to construct
``bob_port_error_probabilities``.

See Also
--------
fa_ddm.vulnerability
    Gaussian-mixture centroids, likelihoods, MAP decisions, and Monte Carlo
    vulnerability estimation.

fa_ddm.quadrature
    Integration bounds and rectangular quadrature-grid construction.

fa_ddm.channel
    Bob-oriented phase precoding and effective Eve-side channels.

fa_ddm.bounds
    Total-variation and permutation-based vulnerability bounds.

scripts.run_figure_05
    Reproducible privacy-reliability optimization and benchmark experiment.
"""


import numpy as np
from scipy.optimize import linprog
from scipy.special import erfc

from fa_ddm.quadrature import integration_bounds, rectangular_quadrature_grid
from fa_ddm.vulnerability import mixture_centroids


def q_function(x):
    """Return the Gaussian Q-function."""
    return 0.5 * erfc(np.asarray(x, dtype=float) / np.sqrt(2.0))


def qpsk_symbol_error_probabilities(
    bob_channel, transmit_power, noise_variance_bob
):
    """Return coherent QPSK symbol-error probability for every port.

    For port n, gamma_n = P_t |h_B,n|^2 / sigma_B^2 and
    P_e,n = 2 Q(sqrt(gamma_n)) - Q^2(sqrt(gamma_n)).
    """
    bob_channel = np.asarray(bob_channel, dtype=np.complex128)
    if bob_channel.ndim != 1 or bob_channel.size == 0:
        raise ValueError("bob_channel must be a nonempty 1-D array.")
    if transmit_power <= 0.0 or noise_variance_bob <= 0.0:
        raise ValueError("power and noise variance must be positive.")
    gamma = transmit_power * np.abs(bob_channel) ** 2 / noise_variance_bob
    q_values = q_function(np.sqrt(gamma))
    return 2.0 * q_values - q_values ** 2


def likelihood_coefficients(
    observations,
    symbols,
    effective_eve_channel,
    symbol_probabilities,
    transmit_power,
    noise_variance_eve,
):
    """Return coefficients C[r,m,n] such that ell_m(y_r)=sum_n C[r,m,n]rho_n."""
    observations = np.asarray(observations, dtype=np.complex128)
    symbols = np.asarray(symbols, dtype=np.complex128)
    effective_channel = np.asarray(effective_eve_channel, dtype=np.complex128)
    priors = np.asarray(symbol_probabilities, dtype=float)
    if observations.ndim != 1:
        raise ValueError("observations must be one-dimensional.")
    if priors.shape != (symbols.size,) or not np.isclose(priors.sum(), 1.0):
        raise ValueError("symbol_probabilities are invalid.")
    if noise_variance_eve <= 0.0:
        raise ValueError("noise_variance_eve must be positive.")

    centroids = mixture_centroids(symbols, effective_channel, transmit_power)
    displacement = observations[:, None, None] - centroids[None, :, :]
    densities = np.exp(
        -(np.abs(displacement) ** 2) / noise_variance_eve
    ) / (np.pi * noise_variance_eve)
    return densities * priors[None, :, None]


def optimize_port_probabilities(
    symbols,
    effective_eve_channel,
    symbol_probabilities,
    transmit_power,
    noise_variance_eve,
    bob_port_error_probabilities,
    maximum_bob_error,
    points_per_axis=61,
    noise_margin_sigma=5.0,
):
    """Solve the quadrature epigraph LP for privacy-aware port selection.

    Returns a dictionary containing the optimal probability vector and the
    quadrature objective value.
    """
    symbols = np.asarray(symbols, dtype=np.complex128)
    effective_channel = np.asarray(effective_eve_channel, dtype=np.complex128)
    bob_errors = np.asarray(bob_port_error_probabilities, dtype=float)
    number_of_ports = effective_channel.size
    if bob_errors.shape != (number_of_ports,):
        raise ValueError("bob_port_error_probabilities has an invalid shape.")
    if maximum_bob_error < np.min(bob_errors) - 1e-12:
        raise ValueError("maximum_bob_error makes the problem infeasible.")

    centroids = mixture_centroids(symbols, effective_channel, transmit_power)
    bounds = integration_bounds(
        centroids, noise_variance_eve, noise_margin_sigma
    )
    observations, weights = rectangular_quadrature_grid(
        bounds, points_per_axis
    )
    coefficients = likelihood_coefficients(
        observations,
        symbols,
        effective_channel,
        symbol_probabilities,
        transmit_power,
        noise_variance_eve,
    )

    number_of_nodes = observations.size
    number_of_symbols = symbols.size
    number_of_variables = number_of_ports + number_of_nodes

    objective = np.zeros(number_of_variables, dtype=float)
    objective[number_of_ports:] = weights

    # For every (r,m): sum_n C[r,m,n] rho_n - t_r <= 0.
    rows = number_of_nodes * number_of_symbols
    a_ub = np.zeros((rows + 1, number_of_variables), dtype=float)
    b_ub = np.zeros(rows + 1, dtype=float)
    row = 0
    for node_index in range(number_of_nodes):
        for symbol_index in range(number_of_symbols):
            a_ub[row, :number_of_ports] = coefficients[
                node_index, symbol_index, :
            ]
            a_ub[row, number_of_ports + node_index] = -1.0
            row += 1

    # Bob reliability: sum_n rho_n P_e,n <= epsilon_B.
    a_ub[-1, :number_of_ports] = bob_errors
    b_ub[-1] = float(maximum_bob_error)

    a_eq = np.zeros((1, number_of_variables), dtype=float)
    a_eq[0, :number_of_ports] = 1.0
    b_eq = np.array([1.0])
    variable_bounds = [(0.0, 1.0)] * number_of_ports + [
        (0.0, None)
    ] * number_of_nodes

    result = linprog(
        objective,
        A_ub=a_ub,
        b_ub=b_ub,
        A_eq=a_eq,
        b_eq=b_eq,
        bounds=variable_bounds,
        method="highs",
    )
    if not result.success:
        raise RuntimeError("Port-selection LP failed: {0}".format(result.message))

    rho = result.x[:number_of_ports]
    return {
        "rho": rho,
        "vulnerability": float(result.fun),
        "bob_error": float(np.dot(rho, bob_errors)),
        "status": result.message,
    }
